// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\0\1\5\5\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\11\1\13\1\14\1\15\11\16\1\0\1\17\1\0"+
    "\1\20\3\0\1\21\1\22\1\23\1\24\1\25\3\23"+
    "\1\26\2\23\1\27\1\30\1\23\1\31\1\32\1\23"+
    "\1\33\1\34\2\23\1\35\4\23\1\36\1\0\1\36"+
    "\1\0\1\37\1\0\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\23\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\23\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\23\1\67\1\0\1\70"+
    "\7\0\1\3\113\0\1\23\37\0\1\23\u0136\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\5\2\10\1\11\5\1\1\12\21\1\1\13"+
    "\1\14\2\0\1\2\21\0\1\15\6\0\1\15\25\0"+
    "\2\16\1\0\1\16\26\0\1\17\17\0\1\2\2\20"+
    "\1\16\7\0\1\17\17\0\1\20\1\16\5\0\1\15"+
    "\6\0\1\15\1\0\1\15\1\0\1\20\1\16\4\0"+
    "\1\15\10\0\1\20\4\0\1\21\47\0\1\15\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\71\0\162\0\253\0\71\0\71\0\71"+
    "\0\71\0\71\0\344\0\71\0\u011d\0\71\0\u0156\0\u018f"+
    "\0\u01c8\0\u0201\0\u023a\0\71\0\u0273\0\u02ac\0\u02e5\0\u031e"+
    "\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\71\0\253"+
    "\0\u0675\0\u06ae\0\u06e7\0\u0156\0\u0720\0\u0759\0\u0792\0\u07cb"+
    "\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993"+
    "\0\u09cc\0\u0a05\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b"+
    "\0\u0b94\0\u0bcd\0\u0156\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea"+
    "\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2"+
    "\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\u107a"+
    "\0\u10b3\0\u10ec\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209"+
    "\0\u1242\0\u127b\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\u13d1"+
    "\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599"+
    "\0\u04ad\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef\0\u1728"+
    "\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0"+
    "\0\u1929\0\u1962\0\u1041\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f"+
    "\0\u1ab8\0\u1af1\0\u1b2a\0\u1b63\0\u1b9c\0\u0156\0\u1bd5\0\u1c0e"+
    "\0\u1c47\0\u1c80\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d\0\u1dd6"+
    "\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65\0\u1f9e"+
    "\0\u1fd7\0\u2010\0\u2049\0\u2082\0\u20bb\0\u20f4\0\u212d\0\u2166"+
    "\0\u219f\0\u21d8\0\u2211\0\u224a\0\u2283\0\u12b4\0\u22bc\0\u22f5"+
    "\0\u232e\0\u2367\0\u23a0\0\u23d9\0\u2412\0\u244b\0\u2484\0\u24bd"+
    "\0\u24f6\0\u252f\0\u2568\0\u25a1\0\u25da\0\u2613\0\u264c\0\u2685"+
    "\0\u26be\0\u26f7\0\u2730\0\u2769\0\u27a2\0\u27db\0\u2814\0\u284d"+
    "\0\u2886\0\u28bf\0\u28f8\0\u2931\0\u296a\0\u29a3\0\u29dc\0\u2a15"+
    "\0\u2a4e\0\u2a87\0\u2ac0\0\u2af9\0\u2b32\0\u2b6b\0\u2ba4\0\u2bdd"+
    "\0\u2c16\0\u2c4f\0\u2c88\0\u2cc1\0\u2cfa\0\u2d33\0\u2d6c\0\u2da5"+
    "\0\u2dde\0\u2e17\0\u2e50\0\u2e89\0\u2ec2\0\u2efb\0\u2f34\0\u2f6d"+
    "\0\u2fa6\0\u2fdf\0\u3018\0\71\0\u3018";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\2\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\2\1\17"+
    "\1\20\3\17\1\21\1\17\1\22\3\17\1\23\1\17"+
    "\1\24\1\17\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\2\17\1\33\1\17\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\17\1\44\1\45\2\17\1\46"+
    "\1\47\73\0\1\3\66\0\5\50\1\3\63\50\10\0"+
    "\1\51\3\0\1\52\71\0\2\15\53\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\30\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\23\54\1\56\4\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\10\54\1\57\4\54"+
    "\1\0\15\54\1\60\12\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\1\54\1\61"+
    "\26\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\22\54\1\62\4\54\1\63\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\20\54\1\64\7\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\16\54\1\65"+
    "\1\54\1\66\6\54\1\67\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\1\54\1\70"+
    "\6\54\1\71\2\54\1\72\2\54\1\73\11\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\16\54\1\74\11\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\13\54\1\75"+
    "\12\54\1\76\1\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\1\54\1\77\7\54"+
    "\1\100\1\54\1\101\2\54\1\102\11\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\6\54\1\103\5\54\1\104\1\105\12\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\16\54\1\106\11\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\1\54\1\107\26\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\5\54\1\110\15\54\1\111\4\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\23\54\1\112\4\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\20\54\1\113"+
    "\2\54\1\114\4\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\5\54\1\115\22\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\10\54\1\116\11\54\1\117\1\120\1\54"+
    "\1\121\2\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\10\54\1\122\7\54\1\123"+
    "\7\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\16\54\1\124\11\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\10\54\1\125\17\54\34\0\1\126\36\0\10\127\1\130"+
    "\60\127\2\52\1\3\1\52\1\4\64\52\1\0\2\53"+
    "\1\0\1\53\13\0\1\55\50\0\1\131\1\132\1\133"+
    "\1\131\1\133\47\131\1\134\14\131\1\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\6\54"+
    "\1\135\21\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\4\54\1\136\10\54\1\0\30\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\17\54\1\137\10\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\22\54\1\140"+
    "\5\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\20\54\1\141\7\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\21\54\1\142\6\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\7\54\1\143\20\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\16\54\1\144\11\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\5\54"+
    "\1\145\22\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\22\54\1\146\5\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\21\54\1\147\1\150\5\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\1\54"+
    "\1\151\26\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\1\54\1\152\26\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\15\54\1\153\12\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\23\54\1\154"+
    "\4\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\21\54\1\147\6\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\22\54\1\155\5\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\13\54\1\75\14\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\15\54\1\156\12\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\16\54"+
    "\1\157\11\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\20\54\1\103\7\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\17\54\1\160\10\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\17\54\1\161"+
    "\1\54\1\162\1\163\5\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\15\54\1\164"+
    "\12\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\11\54\1\165\16\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\25\54\1\103\2\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\13\54\1\166\14\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\22\54\1\103\5\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\11\54"+
    "\1\167\16\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\2\54\1\170\25\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\22\54\1\171\5\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\16\54\1\172"+
    "\11\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\1\54\1\173\26\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\17\54\1\174\10\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\11\54\1\175\16\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\11\54\1\143\6\54\1\176\7\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\23\54\1\147\3\54\1\103\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\11\54"+
    "\1\177\16\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\11\54\1\200\16\54\23\0"+
    "\1\201\47\0\10\127\1\202\70\127\1\202\3\127\1\203"+
    "\54\127\2\131\1\0\1\131\1\0\65\131\1\132\1\133"+
    "\1\131\1\133\14\131\15\204\1\131\15\204\1\205\12\204"+
    "\4\131\1\0\1\131\1\0\37\131\1\206\24\131\1\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\6\54\1\207\21\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\26\54\1\210"+
    "\1\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\23\54\1\211\4\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\3\54\1\212\24\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\11\54\1\106\16\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\22\54\1\213\5\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\21\54"+
    "\1\103\6\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\13\54\1\214\14\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\1\54\1\215\26\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\5\54\1\216"+
    "\22\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\5\54\1\103\22\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\3\54\1\217\24\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\20\54\1\216\7\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\21\54\1\220\6\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\22\54"+
    "\1\221\5\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\2\54\1\222\25\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\5\54\1\223\22\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\1\54\1\224"+
    "\2\54\1\103\23\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\1\54\1\225\26\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\13\54\1\226\14\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\22\54"+
    "\1\227\5\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\5\54\1\230\22\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\7\54\1\216\20\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\15\54\1\103"+
    "\12\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\13\54\1\103\14\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\15\54\1\231\12\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\13\54\1\232\14\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\23\54\1\233\4\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\20\54"+
    "\1\225\7\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\22\54\1\232\5\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\5\54\1\102\22\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\22\54\1\150"+
    "\5\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\16\54\1\234\11\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\4\54\1\103\23\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\13\54\1\147\14\54"+
    "\31\0\1\235\41\0\10\127\1\202\3\127\1\3\54\127"+
    "\2\131\1\0\1\131\1\0\10\131\2\204\2\131\15\204"+
    "\1\131\30\204\4\131\1\0\1\131\1\0\10\131\2\204"+
    "\2\131\15\204\1\131\5\204\1\236\22\204\4\131\1\0"+
    "\1\131\1\0\57\131\1\237\4\131\1\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\5\54"+
    "\1\240\22\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\3\54\1\241\24\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\22\54\1\242\5\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\10\54\1\174"+
    "\17\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\5\54\1\243\22\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\5\54\1\244\22\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\12\54\1\103\15\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\10\54\1\103\17\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\21\54"+
    "\1\245\6\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\11\54\1\246\16\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\13\54\1\146\14\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\15\54\1\247"+
    "\12\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\13\54\1\250\14\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\22\54\1\216\5\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\5\54\1\251\22\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\1\54\1\252\26\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\20\54"+
    "\1\253\7\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\22\54\1\254\5\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\11\54\1\255\16\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\20\54\1\165"+
    "\7\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\25\54\1\256\2\54\23\0\1\257"+
    "\47\0\2\131\1\0\1\131\1\0\10\131\2\204\2\131"+
    "\15\204\1\131\25\204\1\260\2\204\3\131\1\261\1\262"+
    "\1\131\1\262\64\131\1\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\20\54\1\263\7\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\5\54\1\264\22\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\13\54\1\265\1\54"+
    "\1\0\30\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\14\54\1\266\13\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\1\54\1\267\26\54\3\0\2\270\1\0\1\270"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\30\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\15\54\1\271\12\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\4\54\1\143"+
    "\23\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\13\54\1\272\14\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\14\54\1\273\13\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\15\54\1\274\12\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\6\54\1\275\21\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\13\54"+
    "\1\165\14\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\3\54\1\103\24\54\24\0"+
    "\1\276\46\0\1\131\1\261\1\262\1\131\1\262\10\131"+
    "\2\204\2\131\15\204\1\131\30\204\3\131\1\261\1\262"+
    "\1\131\1\262\14\131\15\204\1\131\30\204\2\131\1\0"+
    "\2\262\1\0\1\262\14\0\15\277\1\0\30\277\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\5\54\1\300\22\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\17\54\1\301"+
    "\10\54\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\22\54\1\302\5\54\3\0\2\53"+
    "\1\0\1\53\6\0\1\303\1\0\2\54\1\0\1\55"+
    "\15\54\1\0\30\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\15\54\1\216\12\54"+
    "\3\0\2\270\1\0\1\270\13\0\1\55\15\304\1\0"+
    "\30\304\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\23\54\1\147\4\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\27\54\1\103\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\5\54\1\305\22\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\3\54\1\306\24\54\3\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\1\54\1\307"+
    "\26\54\35\0\1\310\52\0\2\277\2\0\15\277\1\0"+
    "\30\277\3\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\15\54\1\0\4\54\1\311\23\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\22\54\1\312\5\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\20\54\1\313\7\54"+
    "\57\0\1\314\30\0\2\304\2\0\15\304\1\0\30\304"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\15\54\1\315\12\54\3\0\2\53\1\0"+
    "\1\53\10\0\2\54\1\0\1\55\15\54\1\0\5\54"+
    "\1\316\22\54\3\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\3\54\1\147\24\54\23\0"+
    "\1\317\50\0\2\53\1\0\1\53\10\0\2\54\1\0"+
    "\1\55\12\54\1\320\2\54\1\0\30\54\3\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\11\54\1\321\16\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\5\54\1\322\22\54"+
    "\64\0\1\323\7\0\2\53\1\0\1\53\10\0\2\54"+
    "\1\0\1\55\15\54\1\0\22\54\1\143\5\54\3\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\16\54\1\324\11\54\41\0\1\325\32\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\5\54\1\326\22\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\16\54\1\165\11\54"+
    "\3\0\2\53\1\0\1\53\10\0\2\54\1\0\1\55"+
    "\15\54\1\0\1\54\1\327\26\54\63\0\1\330\10\0"+
    "\2\53\1\0\1\53\10\0\2\54\1\0\1\55\15\54"+
    "\1\0\6\54\1\103\21\54\35\0\1\331\36\0\2\53"+
    "\1\0\1\53\10\0\2\54\1\0\1\55\15\54\1\0"+
    "\1\54\1\332\26\54\3\0\2\53\1\0\1\53\10\0"+
    "\2\54\1\0\1\55\15\54\1\0\14\54\1\311\13\54"+
    "\15\0\1\333\102\0\1\334\44\0\2\53\1\0\1\53"+
    "\10\0\2\54\1\0\1\55\15\54\1\0\4\54\1\174"+
    "\23\54\60\0\1\335\46\0\1\336\113\0\1\337\36\0"+
    "\1\340\113\0\1\341\53\0\1\342\111\0\1\343\51\0"+
    "\1\344\114\0\1\345\30\0\1\346\121\0\1\347\42\0"+
    "\1\350\120\0\1\351\35\0\1\352\50\0\2\351\1\0"+
    "\1\351\1\0\1\353\152\0\1\354\2\353\1\0\1\353"+
    "\1\0\2\353\1\355\61\353";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12369];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\5\11\1\1\1\11\1\1\1\11"+
    "\5\1\1\11\22\1\1\11\2\0\1\1\21\0\1\1"+
    "\6\0\1\1\25\0\2\1\1\0\1\1\26\0\1\1"+
    "\17\0\4\1\7\0\1\1\17\0\2\1\5\0\1\1"+
    "\6\0\1\1\1\0\1\1\1\0\2\1\4\0\1\1"+
    "\10\0\1\1\4\0\1\1\47\0\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[237];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 19: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 20: break;
          case 3:
            { return token(yytext(), "PARENTESIS_ABRE", yyline, yycolumn);
            }
            // fall through
          case 21: break;
          case 4:
            { return token(yytext(), "PARENTESIS_CIERRA", yyline, yycolumn);
            }
            // fall through
          case 22: break;
          case 5:
            { return token(yytext(), "OPERADOR_ARIT", yyline, yycolumn);
            }
            // fall through
          case 23: break;
          case 6:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
            // fall through
          case 24: break;
          case 7:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
            // fall through
          case 25: break;
          case 8:
            { return token(yytext(), "NUMERO", yyline, yycolumn);
            }
            // fall through
          case 26: break;
          case 9:
            { return token(yytext(), "PUNTO_COMA", yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 10:
            { return token(yytext(), "CORCHETE_CIERRA", yyline, yycolumn);
            }
            // fall through
          case 28: break;
          case 11:
            { return token(yytext(), "LLAVE_ABRE", yyline, yycolumn);
            }
            // fall through
          case 29: break;
          case 12:
            { return token(yytext(), "LAVVE_CIERRA", yyline, yycolumn);
            }
            // fall through
          case 30: break;
          case 13:
            { return token(yytext(), "IDENTIFICADOR", yyline, yycolumn);
            }
            // fall through
          case 31: break;
          case 14:
            { return token(yytext().substring(yytext().indexOf("=") + 1).trim(), "ASIGNACION_DER", yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 15:
            { return token(yytext(), "TIPO_DATO", yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 16:
            { return token(yytext(), "CONSTRUCCION_OBJETO", yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 17:
            { return token(yytext().substring(6).trim(), "NOMBRE_CLASE", yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 18:
            { return token("System.out.println", "FUNCION_IMPRIMIR", yyline, yycolumn);
            }
            // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
